<?php

namespace financas_api\conf;

class Parameters
{
    static $DECIMAL_PRECISION = 2;

    static $FIRST_DAY_OF_MONTH = 7;

    static $GROUP_BY_KEY_WALLET = "WALLET";
    static $GROUP_BY_KEY_OWNER = "OWNER";
    static $GROUP_BY_KEY_PAYMENTMETHOD = "PAYMENT_METHOD";
    static $GROUP_BY_KEY_TRANSACTIONTYPE = "TRANSACTION_TYPE";
    static $GROUP_BY_KEY_TRANSACTION = "TRANSACTION";
    static $GROUP_BY_KEY_INSTALLMENT = "INSTALLMENT";
    static $GROUP_BY_KEY_DAY = "DAY";
    static $GROUP_BY_KEY_MONTH = "MONTH";
    
    static $REPORTS_KEY_GROUP_WALLET = "WALLET";
    static $REPORTS_KEY_GROUP_OWNER = "OWNER";
    static $REPORTS_KEY_GROUP_PAYMENTMETHOD = "PAYMENT_METHOD";
    static $REPORTS_KEY_GROUP_TRANSACTIONTYPE = "TRANSACTION_TYPE";
    static $REPORTS_KEY_GROUP_TRANSACTION = "TRANSACTION";
    static $REPORTS_KEY_GROUP_INSTALLMENT = "INSTALLMENT";
    static $REPORTS_KEY_GROUP_DAY = "DAY";
    static $REPORTS_KEY_GROUP_MONTH = "MONTH";

    static $REPORTS_KEY_START_AT = "START_AT";
}

?>